=== Abinandhini-cpu/ChainsKotlin/tools/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","chain","rpc","nativeCurrency","chainId","networkId"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "nativeCurrency":{
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "shortName":{
            "type":"string"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string"
                    }
                }
            }
        }
    }
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-12553.json
{
  "name": "RSS3 VSL Mainnet",
  "chain": "RSS3",
  "rpc": ["https://rpc.mainnet.rss3.io"],
  "faucets": [],
  "nativeCurrency": {
    "name": "RSS3",
    "symbol": "RSS3",
    "decimals": 18
  },
  "infoURL": "https://rss3.io",
  "shortName": "rss3",
  "chainId": 12553,
  "networkId": 12553,
  "icon": "rss3",
  "explorers": [
    {
      "name": "RSS3 VSL Scan",
      "url": "https://scan.mainnet.rss3.io",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-3127.json
{
  "name": "Planet Memes Chain",
  "chain": "PMC",
  "rpc": ["https://rpc.planetmemes.com"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Planet Memes Chain",
    "symbol": "PMC",
    "decimals": 18
  },
  "infoURL": "https://planetmemes.com",
  "shortName": "PMC",
  "chainId": 3127,
  "networkId": 3127,
  "icon": "pmc",
  "explorers": [
    {
      "name": "Planet memes chain (PMC) Explorer",
      "url": "https://pmcscan.com",
      "icon": "pmc",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-14093.json
{
  "name": "EightBox Testnet",
  "chain": "EGB-Testnet",
  "rpc": ["https://rpc.eightbox.org"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Eightbox Testnet",
    "symbol": "EGB",
    "decimals": 18
  },
  "infoURL": "https://eightbox.org",
  "shortName": "Eightbox-Testnet",
  "chainId": 14093,
  "networkId": 14093,
  "explorers": [
    {
      "name": "Eightbox Testnet Explorer",
      "url": "https://testnet.eightbox.org",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-142857.json
{
  "name": "ICPlaza Mainnet",
  "chain": "ICPlaza",
  "icon": "ICPlaza",
  "rpc": ["https://rpcmainnet.ic-plaza.org/"],
  "faucets": [],
  "nativeCurrency": {
    "name": "ict",
    "symbol": "ict",
    "decimals": 18
  },
  "infoURL": "https://docs.ic-plaza.org/",
  "shortName": "ICPlaza",
  "chainId": 142857,
  "networkId": 142857,
  "explorers": [
    {
      "name": "ICPlaza",
      "url": "https://browseevm.ic-plaza.org/",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-43288.json
{
  "name": "Bobaavax",
  "chain": "Bobaavax",
  "rpc": [
    "https://avax.boba.network",
    "wss://wss.avax.boba.network",
    "https://replica.avax.boba.network",
    "wss://replica-wss.avax.boba.network"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Boba Token",
    "symbol": "BOBA",
    "decimals": 18
  },
  "infoURL": "https://boba.network",
  "shortName": "Bobaavax",
  "chainId": 43288,
  "networkId": 43288,
  "explorers": [
    {
      "name": "Bobaavax block explorer",
      "url": "https://blockexplorer.avax.boba.network",
      "standard": "none"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-203.json
{
  "name": "ClearBlocker",
  "chain": "CLR",
  "rpc": ["https://rpc.clearblocker.com"],
  "faucets": [],
  "nativeCurrency": {
    "name": "ClearBlocker Coin",
    "symbol": "CLR",
    "decimals": 18
  },
  "infoURL": "https://clearblocker.com",
  "shortName": "clr",
  "icon": "clear",
  "chainId": 203,
  "networkId": 203,
  "explorers": [
    {
      "name": "ClearBlocker Explorer",
      "url": "https://explorer.clearblocker.com",
      "icon": "clear",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-30103.json
{
  "name": "Cerium Testnet",
  "chain": "CAU",
  "icon": "canxium",
  "rpc": ["https://cerium-rpc.canxium.net"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Canxium",
    "symbol": "CAU",
    "decimals": 18
  },
  "infoURL": "https://canxium.org",
  "shortName": "cau",
  "chainId": 30103,
  "networkId": 30103,
  "explorers": [
    {
      "name": "canxium explorer",
      "url": "https://cerium-explorer.canxium.net",
      "standard": "none"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-5845.json
{
    "name": "Tangle Mainnet",
    "chain": "Tangle",
    "rpc": [
        "https://rpc.tangle.tools",
        "https://rpc-archive.tangle.tools",
        "wss://rpc.tangle.tools",
        "wss://rpc-archive.tangle.tools"
      ],
    "faucets": [],
    "nativeCurrency": {
      "name": "Tangle",
      "symbol": "TNT",
      "decimals": 18
    },
    "infoURL": "https://docs.tangle.tools",
    "shortName": "tangle-mainnet",
    "chainId": 5845,
    "networkId": 5845,
    "icon": "tangle",
    "explorers": [
      {
        "name": "Tangle EVM Explorer",
        "url": "https://explorer.tangle.tools",
        "standard": "EIP3091",
        "icon": "tangle"
      }
    ]
  }
