=== Abinandhini-cpu/ChainsKotlin/tools/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","chain","rpc","nativeCurrency","chainId","networkId"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "nativeCurrency":{
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "shortName":{
            "type":"string"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string"
                    }
                }
            }
        }
    }
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-11214.json
{
  "name": "SerenityEnergy Mainnet",
  "chain": "ERGON",
  "rpc": [
    "https://serenity.ing/rpc"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "SerenityEnergy",
    "symbol": "SET",
    "decimals": 18
  },
  "infoURL": "https://serenity.energy",
  "shortName": "set",
  "chainId": 11214,
  "networkId": 11214,
  "icon": "ergon",
  "explorers": [{
    "name": "serenity block explorer",
    "url": "https://serenity.ing/explorer",
    "icon": "ergon",
    "standard": "EIP3091"
  }]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-128123.json
{
  "name": "Etherlink Testnet",
  "chain": "XTZ",
  "icon": "etherlink",
  "chainId": 128123,
  "networkId": 128123,
  "infoURL": "https://docs.etherlink.com",
  "shortName": "etherlink-testnet",
  "nativeCurrency": {
    "name": "tez",
    "symbol": "XTZ",
    "decimals": 18
  },
  "rpc": ["https://node.ghostnet.etherlink.com"],
  "faucets": ["https://faucet.etherlink.com/"],
  "explorers": [
    {
      "name": "EtherScout Testnet Explorer",
      "url": "https://explorer.etherlink.com",
      "standard": "EIP1559"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-11221.json
{
  "name": "Shine Chain",
  "chain": "Shine",
  "rpc": ["https://rpc.shinescan.io"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Shine",
    "symbol": "SC20",
    "decimals": 18
  },
  "infoURL": "https://shinechain.tech",
  "shortName": "SC20",
  "chainId": 11221,
  "networkId": 11221,
  "icon": "shine",
  "explorers": [
    {
      "name": "Shine Explorer",
      "url": "https://shinescan.io",
      "icon": "shine",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-4321.json
{
  "name": "Metabit Chain Mainnet",
  "chain": "Metabit",
  "icon": "metabit",
  "rpc": [
    "https://mainnet.rpc.metabitglobal.com"
  ],
  "faucets": [
    
  ],
  "nativeCurrency": {
    "name": "Metabit Chain Native Token",
    "symbol": "BMTC",
    "decimals": 18
  },
  "infoURL": "https://metabitglobal.com",
  "shortName": "MetabitMainnet",
  "chainId": 4321,
  "networkId": 4321,
  "explorers": [
    {
      "name": "metabit_explorer",
      "url": "https://metabitglobal.io",
      "standard": "none"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-71213.json
{
  "name": "Trendz Blockchain Testnet",
  "chain": "Trendz Blockchain",
  "icon": "trendz",
  "rpc": ["https://t-rpc.trendzblockchain.com"],
  "faucets": ["https://t-faucet.trendzblockchain.com"],
  "nativeCurrency": {
    "name": "TRB",
    "symbol": "TRB",
    "decimals": 18
  },
  "infoURL": "https://www.trendzblockchain.co",
  "shortName": "TRB",
  "chainId": 71213,
  "networkId": 71213,
  "explorers": [
    {
      "name": "Trendz Blockchain Testnet Explorer",
      "url": "https://t-scan.trendzblockchain.com/",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-355115.json
{
  "name": "Bitfinity Network",
  "chain": "BFT",
  "rpc": ["https://rpc.bitfinity.network"],
  "faucets": ["https://bitfinity.network/faucet"],
  "nativeCurrency": {
    "name": "BITFINITY",
    "symbol": "BFT",
    "decimals": 18
  },
  "infoURL": "https://bitfinity.network",
  "shortName": "Bitfinity",
  "chainId": 355115,
  "networkId": 355115,
  "explorers": [
    {
      "name": "Bitfinity Block Explorer",
      "url": "https://explorer.bitfinity.network",
      "icon": "bitfinity",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-444.json
{
  "name": "Urbit Virtual Machine",
  "chain": "UVM",
  "icon": "uvm",
  "rpc": ["https://rpc.uvm.network/"],
  "faucets": [],
  "nativeCurrency": {
    "name": "$U",
    "symbol": "U",
    "decimals": 18
  },
  "infoURL": "https://uvm.network",
  "shortName": "uvm",
  "chainId": 444,
  "networkId": 444,
  "explorers": [
    {
      "name": "UVMScan",
      "url": "https://explorer.uvm.network",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-19515.json
{
  "name": "SEC Testnet",
  "chain": "SEC",
  "icon": "dcpayIcon",
  "rpc": ["https://testnet-rpc.secexplorer.io"],
  "faucets": ["https://faucet.secexplorer.io"],
  "nativeCurrency": {
    "name": "SEP",
    "symbol": "SEP",
    "decimals": 18
  },
  "infoURL": "https://smartenergychain.org",
  "shortName": "SECt",
  "chainId": 19515,
  "networkId": 19515,
  "explorers": [
    {
      "name": "SEC Testnet Explorer",
      "url": "https://testnet.secexplorer.io",
      "standard": "EIP3091"
    }
  ]
}
