=== Abinandhini-cpu/ChainsKotlin/tools/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","chain","rpc","nativeCurrency","chainId","networkId"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "nativeCurrency":{
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "shortName":{
            "type":"string"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string"
                    }
                }
            }
        }
    }
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-3335.json
{
  "name": "EthStorage Devnet",
  "chain": "EthStorage",
  "rpc": ["http://devnet.ethstorage.io:9540"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://ethstorage.io/",
  "shortName": "es-d",
  "chainId": 3335,
  "networkId": 3335,
  "slip44": 1
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-20000.json
{
  "name": "DogeChain",
  "chain": "DogeChain",
  "rpc": ["https://rpc.ankr.com/dogechain"],
  "faucets": [],
  "nativeCurrency": {
    "name": "wDoge",
    "symbol": "wDOGE",
    "decimals": 18
  },
  "infoURL": "https://dogechain.dog",
  "shortName": "DC",
  "chainId": 20000,
  "networkId": 20000,
  "explorers": [
    {
      "name": "dogechain explorer",
      "url": "https://explorer.dogechain.dog",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/eip155-789789.json
{
  "name": "The Ting Blockchain Testnet",
  "chain": "Ting",
  "rpc": ["https://testnet.tingchain.org/"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ton",
    "symbol": "Ton",
    "decimals": 18
  },
  "infoURL": "https://tingscan.com/",
  "shortName": "tingtest",
  "chainId": 6666689,
  "networkId": 6666689,
  "explorers": [
    {
      "name": "TingScan",
      "url": "https://tingscan.com/",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-1107.json
{
  "name": "BLXq Testnet",
  "chain": "BLXQ",
  "rpc": [
    "https://testnetq1.blx.org"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "BLXQ",
    "symbol": "BLXQ",
    "decimals": 18
  },
  "infoURL": "https://blx.org",
  "shortName": "blxq",
  "chainId": 1107,
  "networkId": 1107,
  "icon": "blxq",
  "explorers": [{
    "name": "BLXq Explorer",
    "url": "https://explorer.blx.org",
    "icon": "blxq",
    "standard": "EIP3091"
  }]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-16969696.json
{
  "name": " Privix Chain Mainnet",
  "chain": "PSC",
  "rpc": [
    "https://mainnet-rpc.privixchain.xyz/",
    "wss://mainnet-rpc.privixchain.xyz/ws"
  ],
  "faucets": ["https://faucet.privixchain.xyz"],
  "nativeCurrency": {
    "name": "Privix Coin",
    "symbol": "PSC",
    "decimals": 18
  },
  "infoURL": "https://privix.co/",
  "shortName": "mpsc",
  "chainId": 16969696,
  "networkId": 16969696,
  "icon": "privix",
  "explorers": [
    {
      "name": "blockscout",
      "url": "https://mainnet.privixscan.io",
      "icon": "blockscout",
      "standard": "EIP3091"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-3389.json
{
  "name": "Fomochain Testnet",
  "chain": "Fomochain",
  "rpc": [
    "https://testnet.fomochain.us"
  ],
  "faucets": [
    "https://faucet.fomochain.us",
    "https://fauceth.komputing.org?chain=16&address=${ADDRESS}"
  ],
  "nativeCurrency": {
    "name": "FomoChain",
    "symbol": "FOMO",
    "decimals": 18
  },
  "infoURL": "https://docs.fomochain.us",
  "shortName": "",
  "chainId": 3389,
  "networkId": 3389,
  "explorers": [{
    "name": "blockscout",
    "url": "https://fomoscan.fomochain.us",
    "standard": "EIP3091"
  }]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-820522.json
{
  "name": "TSC Testnet",
  "chain": "TSC Testnet",
  "rpc": ["https://testnet.tscscan.io/testrpc"],
  "faucets": [],
  "nativeCurrency": {
    "name": "TAS",
    "symbol": "tTAS",
    "decimals": 18
  },
  "infoURL": "https://www.trias.one/",
  "shortName": "netx",
  "icon": "netx",
  "chainId": 820522,
  "networkId": 820025,
  "explorers": [
    {
      "name": "tscscan",
      "url": "https://testnet.tscscan.io/",
      "icon": "netxscan",
      "standard": "none"
    }
  ]
}

=== Abinandhini-cpu/ChainsKotlin/_data/chains/eip155-308.json
{
    "name": "Furtheon",
    "chain": "Furtheon Network",
    "icon": "furtheon",
    "rpc": [
      "https://rpc.furtheon.org"
    ],
    "faucets": [],
    "nativeCurrency": {
      "name": "Furtheon",
      "symbol": "FTH",
      "decimals": 18
    },
    "infoURL": "https://furtheon.org/",
    "shortName": "furtheon",
    "chainId": 308,
    "networkId": 308,
    "explorers": [
      {
        "name": "furthscan",
        "url": "http://furthscan.com",
        "standard": "EIP3091"
      }
    ]
  }
